### ISSUE TITLE
CT cannot read property dataStream of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#258]
Also in Basics and Atomic Interactions
```
states-of-matter : fuzz : built-phet-io : load
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read property 'dataStream' of undefined
TypeError: Cannot read property 'dataStream' of undefined
    at e.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:272548)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:229151)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:228632)
    at Array.r.changeListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:574498)
    at e.trigger0 (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:489935)
    at e.setPickable (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:73473)
    at e.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:73520)
    at f (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:1190294)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:229973)
    at e.vf [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:1190351)
id: Bayes Chrome
Approximately 2/27/2020, 8:13:24 PM
states-of-matter : fuzz : built-phet-io : run
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read property 'dataStream' of undefined
TypeError: Cannot read property 'dataStream' of undefined
    at e.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:272548)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:229151)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:228632)
    at Array.r.changeListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:574498)
    at e.trigger0 (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:489935)
    at e.setPickable (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:73473)
    at e.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:73520)
    at f (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:1190294)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:229973)
    at e.vf [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546-phet-io/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:910:1190351)
id: Bayes Chrome
Approximately 2/27/2020, 8:13:24 PM
states-of-matter : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'dataStream' of undefined
TypeError: Cannot read property 'dataStream' of undefined
    at NodeProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/tandem/js/PhetioObject.js:402:21)
    at NodeProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:262:41)
    at NodeProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:175:14)
    at Array.NodeProperty.changeListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/util/NodeProperty.js:52:38)
    at ProjectorModeCheckbox.trigger0 (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Events.js:236:27)
    at ProjectorModeCheckbox.setPickable (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3206:12)
    at ProjectorModeCheckbox.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3209:32)
    at enabledListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:190:19)
    at BooleanProperty.link (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:357:5)
    at new Checkbox (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:193:24)
id: Bayes Chrome
Approximately 2/27/2020, 8:13:24 PM
states-of-matter : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'dataStream' of undefined
TypeError: Cannot read property 'dataStream' of undefined
    at NodeProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/tandem/js/PhetioObject.js:402:21)
    at NodeProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:262:41)
    at NodeProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:175:14)
    at Array.NodeProperty.changeListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/util/NodeProperty.js:52:38)
    at ProjectorModeCheckbox.trigger0 (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Events.js:236:27)
    at ProjectorModeCheckbox.setPickable (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3206:12)
    at ProjectorModeCheckbox.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3209:32)
    at enabledListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:190:19)
    at BooleanProperty.link (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:357:5)
    at new Checkbox (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:193:24)
id: Bayes Chrome
Approximately 2/27/2020, 8:13:24 PM
states-of-matter : phet-io-state-fuzz : require.js : load
Uncaught Error: Uncaught TypeError: Cannot read property 'dataStream' of undefined
TypeError: Cannot read property 'dataStream' of undefined
    at NodeProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/tandem/js/PhetioObject.js:402:21)
    at NodeProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:262:41)
    at NodeProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:175:14)
    at Array.NodeProperty.changeListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/util/NodeProperty.js:52:38)
    at ProjectorModeCheckbox.trigger0 (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Events.js:236:27)
    at ProjectorModeCheckbox.setPickable (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3206:12)
    at ProjectorModeCheckbox.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3209:32)
    at enabledListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:190:19)
    at BooleanProperty.link (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:357:5)
    at new Checkbox (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:193:24)
id: Bayes Chrome
Approximately 2/27/2020, 8:13:24 PM
states-of-matter : phet-io-state-fuzz : require.js : run
Uncaught Error: Uncaught TypeError: Cannot read property 'dataStream' of undefined
TypeError: Cannot read property 'dataStream' of undefined
    at NodeProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/tandem/js/PhetioObject.js:402:21)
    at NodeProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:262:41)
    at NodeProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:175:14)
    at Array.NodeProperty.changeListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/util/NodeProperty.js:52:38)
    at ProjectorModeCheckbox.trigger0 (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Events.js:236:27)
    at ProjectorModeCheckbox.setPickable (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3206:12)
    at ProjectorModeCheckbox.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3209:32)
    at enabledListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:190:19)
    at BooleanProperty.link (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:357:5)
    at new Checkbox (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:193:24)
id: Bayes Chrome
Approximately 2/27/2020, 8:13:24 PM
states-of-matter : phet-io-studio-fuzz : require.js : load
Uncaught Error: Uncaught TypeError: Cannot read property 'dataStream' of undefined
TypeError: Cannot read property 'dataStream' of undefined
    at NodeProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/tandem/js/PhetioObject.js:402:21)
    at NodeProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:262:41)
    at NodeProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:175:14)
    at Array.NodeProperty.changeListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/util/NodeProperty.js:52:38)
    at ProjectorModeCheckbox.trigger0 (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Events.js:236:27)
    at ProjectorModeCheckbox.setPickable (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3206:12)
    at ProjectorModeCheckbox.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3209:32)
    at enabledListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:190:19)
    at BooleanProperty.link (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:357:5)
    at new Checkbox (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:193:24)
id: Bayes Chrome
Approximately 2/27/2020, 8:13:24 PM
states-of-matter : phet-io-studio-fuzz : require.js : run
Uncaught Error: Uncaught TypeError: Cannot read property 'dataStream' of undefined
TypeError: Cannot read property 'dataStream' of undefined
    at NodeProperty.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/tandem/js/PhetioObject.js:402:21)
    at NodeProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:262:41)
    at NodeProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:175:14)
    at Array.NodeProperty.changeListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/util/NodeProperty.js:52:38)
    at ProjectorModeCheckbox.trigger0 (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Events.js:236:27)
    at ProjectorModeCheckbox.setPickable (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3206:12)
    at ProjectorModeCheckbox.set pickable [as pickable] (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/scenery/js/nodes/Node.js:3209:32)
    at enabledListener (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:190:19)
    at BooleanProperty.link (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/axon/js/Property.js:357:5)
    at new Checkbox (https://bayes.colorado.edu/continuous-testing/snapshot-1582859604546/sun/js/Checkbox.js:193:24)
id: Bayes Chrome
Approximately 2/27/2020, 8:13:24 PM
```

**Comment by chrisklus** [comment]
I needed to fix this for grunt updating all sims. I did one commit for `states-of-matter`, `states-of-matter-basics`, and `atomic-interactions` (since this was the only issue created for all three repos).

@jbphet please review.

**Comment by jbphet** [comment]
Looks reasonable to me.  Closing.
