### ISSUE TITLE
CT Inconsistent number of normalized versus non-normalized particles

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#261]
Also in Basics
```
states-of-matter : phet-io-state-fuzz : require.js : run
Uncaught Error: Assertion failed: Inconsistent number of normalized versus non-normalized particles
Error: Assertion failed: Inconsistent number of normalized versus non-normalized particles
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583748161897/assert/js/assert.js?bust=1583751274962:22:13)
    at MultipleParticleModel.syncParticlePositions (https://bayes.colorado.edu/continuous-testing/snapshot-1583748161897/states-of-matter/js/common/model/MultipleParticleModel.js:1310:15)
    at MultipleParticleModel.stepInternal (https://bayes.colorado.edu/continuous-testing/snapshot-1583748161897/states-of-matter/js/common/model/MultipleParticleModel.js:934:10)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583748161897/states-of-matter/js/common/model/MultipleParticleModel.js:277:12
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1583748161897/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583748161897/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1583748161897/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1583748161897/axon/js/Emitter.js:58:19)
    at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/snapshot-1583748161897/phet-io/js/PhetioStateEngine.js:191:26)
    at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/snapshot-1583748161897/phet-io/js/PhetioEngineIO.js:200:43)
id: Bayes Chrome
Approximately 3/9/2020, 4:02:41 AM
states-of-matter : phet-io-tests : assert
9 out of 9 tests passed. 0 failed.

Approximately 3/9/2020, 4:02:41 AM
states-of-matter : phet-io-tests : no-assert
9 out of 9 tests passed. 0 failed.

Approximately 3/9/2020, 4:02:41 AM
```

**Comment by jbphet** [comment]
CT is showing green for SOM, SOMB, and AI since the commit above was made (14 iterations).  Closing.
