### ISSUE TITLE
CT PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#263]
```
states-of-matter : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/phet-io-wrappers/state/?sim=states-of-matter&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/assert/js/assert.js?bust=1584449522363:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/joist/js/Sim.js:846:48
id: Bayes Chrome
Approximately 3/17/2020, 3:22:31 AM
states-of-matter : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/phet-io-wrappers/state/?sim=states-of-matter&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/assert/js/assert.js?bust=1584449522372:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/joist/js/Sim.js:846:48
id: Bayes Chrome
Approximately 3/17/2020, 3:22:31 AM
states-of-matter : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/studio/?sim=states-of-matter&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/assert/js/assert.js?bust=1584439764133:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/tandem/js/phetioAPIValidation.js:115:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/phet-io/js/phetioEngine.js:158:27
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/TinyEmitter.js:65:53)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/Emitter.js:33:29
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/Action.js:224:18)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/axon/js/Emitter.js:58:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584436951758/joist/js/Sim.js:846:48
id: Bayes Chrome
Approximately 3/17/2020, 3:22:31 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe - I took a look after pulling everything and before the API error I am getting
>Assertion failed: Tandem was required but not supplied
From the AquaRAdioButtonGroup in AtomicInteractionsControlPanel. I think this is related to #245 rather than TimeControlNode changes, but let me know if I can help.

**Comment by jbphet** [comment]
I've updated the API files and the last several rounds of CT have passed.  Closing.
