### ISSUE TITLE
CT Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#270]
```
states-of-matter : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/states-of-matter/states-of-matter_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/tandem/js/phetioAPIValidation.js:116:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:275:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:345:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/12/2020, 7:49:56 PM
states-of-matter : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/states-of-matter/states-of-matter_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/tandem/js/phetioAPIValidation.js:116:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:275:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:345:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/12/2020, 7:49:56 PM
states-of-matter : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io-wrappers/mirror-inputs/?sim=states-of-matter&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/tandem/js/phetioAPIValidation.js:116:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:275:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:345:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/12/2020, 7:49:56 PM
states-of-matter : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io-wrappers/state/?sim=states-of-matter&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/tandem/js/phetioAPIValidation.js:116:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:275:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:345:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/12/2020, 7:49:56 PM
states-of-matter : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/studio/?sim=states-of-matter&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
Error: Assertion failed: PhET-iO API error:
2. Registered PhetioObject baseline must equal baseline schema to ensure that baseline changes are intentional.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/tandem/js/phetioAPIValidation.js:278:15)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/tandem/js/phetioAPIValidation.js:116:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/phet-io/js/phetioEngine.js:158:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/TinyEmitter.js:65:53)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:275:25)
    at Property.set (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:175:14)
    at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/axon/js/Property.js:345:32)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586742596634/joist/js/Sim.js:845:57
id: Bayes Chrome
Approximately 4/12/2020, 7:49:56 PM
```

**Comment by jbphet** [comment]
Updated the API, CT has been clear for two rounds now.  Closing.
