### ISSUE TITLE
State wrapper hits assertion in 1.2 branch 

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#330]
While working to solve https://github.com/phetsims/states-of-matter/issues/322, I tried to checkout the 1.2 release branch and run the "State" wrapper, but when I do the sim crashes with the error:

```
"Assertion failed: value failed isValidValue: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"
```

 The stack trace is:
```
   at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at Object.isValueValid (http://localhost:8080/axon/js/ValidatorDef.js:307:39)
    at validate (http://localhost:8080/axon/js/validate.js:27:18)
    at Function.fromStateObject (http://localhost:8080/tandem/js/types/ArrayIO.js:63:7)
    at MoleculeForceAndMotionDataSet.setState (http://localhost:8080/states-of-matter/js/common/model/MoleculeForceAndMotionDataSet.js:414:54)
    at MultipleParticleModel.applyState (http://localhost:8080/states-of-matter/js/common/model/MultipleParticleModel.js:1432:28)
    at Function.applyState (http://localhost:8080/states-of-matter/js/common/model/MultipleParticleModelIO.js:47:27)
    at PhetioStateEngine.setStateForPhetioObject (http://localhost:8080/phet-io/js/PhetioStateEngine.js:415:10)
    at http://localhost:8080/phet-io/js/PhetioStateEngine.js:315:14
    at Array.forEach (<anonymous>)"
```

After digging into it a bit, I can see that validation of the array that represents the atom positions is failing during setting of state in `MoleculeForceAndMotionDataSet`.

**Comment by jbphet** [comment]
I asked @zepumph to look at this with me, and we concluded that I unfortunately created my release branch while this problem existed in the phet-io code base.  The related issue is https://github.com/phetsims/phet-io/issues/1685.  The commit that fixes the problem is in https://github.com/phetsims/tandem/commit/4bbb2c3f6ef4555c12e4426ab4355072eeedc338.

I'll create a branch of tandem and will cherry-pick this commit and update the dependencies in the branch.

**Comment by zepumph** [comment]
Also see https://github.com/phetsims/QA/issues/530 to make sure this get's tested next time.

**Comment by jbphet** [comment]
Fixed, closing.
