### ISSUE TITLE
CT: Uncaught Error: Cannot read property 'substance' of undefined

### ISSUE THREAD

**Issue by jbphet** [phetsims/states-of-matter#356]
Looks like some of the recent phet-io changes have introduced a CT issue.  This also affects states-of-matter basics.  Below is a stack trace.

```
states-of-matter : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622568194006/phet-io-wrappers/state/?sim=states-of-matter&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1622568194006%22%2C%22timestamp%22%3A1622570067195%7D
Uncaught Error: Cannot read property 'substance' of undefined
TypeError: Cannot read property 'substance' of undefined
at MultipleParticleModel.applyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622568194006/states-of-matter/js/common/model/MultipleParticleModel.js:1397:101)
at Object.applyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622568194006/states-of-matter/js/common/model/MultipleParticleModel.js:1444:73)
at IOType.applyState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622568194006/tandem/js/types/IOType.js:186:14)
at PhetioStateEngine.setStateForPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622568194006/phet-io/js/PhetioStateEngine.js:428:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622568194006/phet-io/js/PhetioStateEngine.js:328:14
at Array.forEach (<anonymous>)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622568194006/phet-io/js/PhetioStateEngine.js:313:22)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622568194006/phet-io/js/PhetioStateEngine.js:247:31)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622568194006/phet-io/js/PhetioStateEngine.js:266:10)
at PhetioEngine.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622568194006/phet-io/js/phetioEngine.js:1011:32)
id: Bayes Chrome
Snapshot from 6/1/2021, 11:23:14 AM
```

**Comment by samreid** [comment]
I ran states of matter through the states wrapper and couldn't see any problems.  It has been clear on CT for the last 20 columns or so, closing.
