### ISSUE TITLE
CT Assertion failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#358]
Also in Basics
```
states-of-matter : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631785713855%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM

----------------------------------

states-of-matter : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631802892825%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM

----------------------------------

states-of-matter : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631798891969%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM

----------------------------------

states-of-matter : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631787311137%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM

----------------------------------

states-of-matter : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631786002199%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM

----------------------------------

states-of-matter : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631786087303%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM

----------------------------------

states-of-matter : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631800882728%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM

----------------------------------

states-of-matter : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/phet-io-wrappers/mirror-inputs/?sim=states-of-matter&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631786220264%7D
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM

----------------------------------

states-of-matter : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/phet-io-wrappers/mirror-inputs/?sim=states-of-matter&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631803193701%7D
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM

----------------------------------

states-of-matter : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/studio/?sim=states-of-matter&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631785736193%7D
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM

----------------------------------

states-of-matter : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/studio/?sim=states-of-matter&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631802845347%7D
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM

----------------------------------

states-of-matter : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1631784832278%22%2C%22timestamp%22%3A1631788128077%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/assert/js/assert.js:25:13)
at Range.getNormalizedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/dot/js/Range.js:205:15)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/scenery-phet/js/ThermometerNode.js:212:31
at getDerivedValue (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:30:10)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:18)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:271:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/Property.js:186:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1631784832278/axon/js/TinyEmitter.js:86:9)
id: Bayes Chrome
Snapshot from 9/16/2021, 3:33:52 AM
```

**Comment by jbphet** [comment]
Something seems very odd here.  Some observations:

- According to the information above, this issue happens in almost every test configuration, yet I can't reproduce it locally.
- The stack track includes `ThermometerNode.js:212:31`, then `Range.js:205:15`, but on master line 212 of `ThermometerNode.js` doesn't call `Range.getNormalizedValue`.
- I set up an experiment where I put a breakpoint at the point in `Range.js` that appears in the stack trace, but that point was never hit during local fuzz testing.

@jonathanolson - Is there something that could be happing in CT where incorrect versions of a common-code repo are being used, or something else that might lead to the weirdness that I've outlined above?

**Comment by jbphet** [comment]
Never mind @jonathanolson - I had some SHAs checked out locally from a recent build that were leading me astray.  I'm back on master and can now duplicate the problem.

**Comment by jbphet** [comment]
He @zepumph - the commit https://github.com/phetsims/scenery-phet/commit/09d11015844aaf26e0811729953d149594351c1a breaks States of Matter.  This is because the temperature value is (or was) allowed to take on a value of `null`.  This was a very intentional choice, meant to be used when there is actually no temperature to be measured.  This occurs in SOM when there are no particles in the container.

Can this be modified to support a nullable value?

**Comment by zepumph** [comment]
What a fun spot where TypeScript will be really, really nice. I didn't even think to check usages because the parameter doc didn't say that null was supported:

https://github.com/phetsims/scenery-phet/blob/09d11015844aaf26e0811729953d149594351c1a/js/ThermometerNode.js#L38


Looks like this was the only place that was documented.

https://github.com/phetsims/scenery-phet/blob/09d11015844aaf26e0811729953d149594351c1a/js/ThermometerNode.js#L249

I update doc, logic, and phet-io support above (with api file). @jbphet please take a look. How does this seem to you?

**Comment by jbphet** [comment]
Thanks @zepumph - the changes look great, and CT is succeeding.  It will indeed be cool if TypeScript can help us avoid situations like this.

Closing.
