### ISSUE TITLE
CT SyntaxError: /data/share/phet/continuous-testing/ct-snapshots/1678078421686/scenery/js/input/SceneryEvent.ts: Unexpected token, expected "," (23:38)

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/states-of-matter#363]
```
states-of-matter : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 78272ms
SyntaxError: /data/share/phet/continuous-testing/ct-snapshots/1678078421686/scenery/js/input/SceneryEvent.ts: Unexpected token, expected "," (23:38)

21 |
22 | // "out" here ensures that SceneryListenerFunctions don't specify a wider type arguments for the event, see https://github.com/phetsims/scenery/issues/1483
> 23 | export default class SceneryEvent<out DOMEvent extends Event = Event> {
| ^
24 |
25 | // Whether this SceneryEvent has been 'handled'. If so, it will not bubble further.
26 | public handled: boolean;
at Object._raise (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/node_modules/@babel/parser/lib/index.js:569:17)
at Object.raiseWithData (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/node_modules/@babel/parser/lib/index.js:562:17)
at Object.raise (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/node_modules/@babel/parser/lib/index.js:523:17)
at Object.unexpected (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/node_modules/@babel/parser/lib/index.js:3601:16)
at Object.expect (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/node_modules/@babel/parser/lib/index.js:3575:28)
at Object.tsParseDelimitedListWorker (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/node_modules/@babel/parser/lib/index.js:7929:14)
at Object.tsParseDelimitedList (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/node_modules/@babel/parser/lib/index.js:7898:25)
at Object.tsParseBracketedList (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/node_modules/@babel/parser/lib/index.js:7951:25)
at Object.tsParseTypeParameters (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/node_modules/@babel/parser/lib/index.js:8063:24)
at Object.tsTryParseTypeParameters (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/node_modules/@babel/parser/lib/index.js:8047:19) {
loc: Position { line: 23, column: 38 },
pos: 1196,
code: 'BABEL_PARSE_ERROR',
reasonCode: 'UnexpectedToken'
}
ERROR
Building runnable repository (states-of-matter, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 15140ms
>> Production minification complete: 71498ms (2351743 bytes)
>> Debug minification complete: 7ms (23316978 bytes)
Building brand: phet-io
>> Webpack build complete: 12947ms
>> Production minification complete: 59625ms (2375071 bytes)
>> Debug minification complete: 61450ms (2673563 bytes)
No migration rules found at ../chipper/dist/js/phet-io-sim-specific/repos/states-of-matter/js/states-of-matter-migration-rules.js, no rules to be bundled with phet-io.js.
>> tsc complete: 15352ms
>> tsc complete: 15231ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/js/grunt/copySupplementalPhetioFiles.js:379:5)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async module.exports (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/js/grunt/buildRunnable.js:371:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/js/grunt/Gruntfile.js:304:15
at async Object.startAsync (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/perennial-alias/js/common/phetTimingLog.js:133:20)
at async /data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/js/grunt/Gruntfile.js:303:13
at async Object.startAsync (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/perennial-alias/js/common/phetTimingLog.js:133:20)
at async /data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/js/grunt/Gruntfile.js:222:7
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1678078421686/chipper/js/grunt/Gruntfile.js:65:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.

Error in fulfilling chunk Promise: [Error: TypeError: r.tandem.createTandem is not a function
at new nn (http://localhost:36222/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:965:1271835)
at new Ay (http://localhost:36222/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:965:1680562)
at http://localhost:36222/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:965:2038906
at window.phet.joist.launchSimulation (http://localhost:36222/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:965:1533445)
at http://localhost:36222/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:965:1533805
at http://localhost:36222/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:965:292116
at Array.forEach (<anonymous>)
at Object.proceedIfReady (http://localhost:36222/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:965:292105)
at Image.<anonymous> (http://localhost:36222/states-of-matter/build/phet-io/states-of-matter_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211&locales=*:965:292208)]
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678082031652%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678094217714%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678106985297%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678091061882%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678104765260%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678084928076%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678093502557%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678082405490%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678095212620%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678106595214%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678082089449%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM

----------------------------------

states-of-matter : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678078421686/states-of-matter/states-of-matter_en.html?continuousTest=%7B%22test%22%3A%5B%22states-of-matter%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1678078421686%22%2C%22timestamp%22%3A1678096928575%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: options.tandem.createTandem is not a function
TypeError: options.tandem.createTandem is not a function
at createTandem (Screen.ts:230:29)
at (AtomicInteractionsScreen.js:37:4)
at (states-of-matter-main.js:46:4)
at callback (simLauncher.ts:67:8)
at launchSimulation (simLauncher.ts:88:26)
at listener (asyncLoader.ts:50:42)
at Array.forEach
at forEach (asyncLoader.ts:50:21)
at proceedIfReady (asyncLoader.ts:63:11)
id: Bayes Puppeteer
Snapshot from 3/5/2023, 9:53:41 PM
```

**Comment by jbphet** [comment]
I was away last week when this was reported, and I just checked CT and the sim appears to be passing.  I'm going to assume that this was a transient thing with some common code and close.
